### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by djarktic** [EducationalTestingService/gitlab-to-atlassian#13]
Retrieving existing Stash projects...done
Processing GitLab projects...
Traceback (most recent call last):
  File "gitlab_to_stash.py", line 273, in <module>
    main()
  File "gitlab_to_stash.py", line 139, in main
    for project in gen_all_results(git.getallprojects,
AttributeError: 'Gitlab' object has no attribute 'getallprojects'

**Comment by desilinguist** [comment]
Unfortunately, this project is not actively maintained since we switched away from GitLab a while ago. It seems that the GitLab API must have changed since this code was written. I updated the project README.
